// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8iNsdD7ZNT8IsG8CWrBj4CvBTgX5Wosc',
    appId: '1:152990228183:web:0128a22113b95462155a92',
    messagingSenderId: '152990228183',
    projectId: 'bitirme-c0dd9',
    authDomain: 'bitirme-c0dd9.firebaseapp.com',
    storageBucket: 'bitirme-c0dd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9bran5gFny8IG8t7j9o91glL3dVl62s',
    appId: '1:152990228183:android:dcef2366e23f030b155a92',
    messagingSenderId: '152990228183',
    projectId: 'bitirme-c0dd9',
    storageBucket: 'bitirme-c0dd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy30YUQmiIW0ZxiJH6T9iQ0crNSnUOOPo',
    appId: '1:152990228183:ios:1da0bfa1ce1109e5155a92',
    messagingSenderId: '152990228183',
    projectId: 'bitirme-c0dd9',
    storageBucket: 'bitirme-c0dd9.firebasestorage.app',
    iosClientId: '152990228183-mf34pbmpvs84gn2f2tq100u87f0vg61o.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy30YUQmiIW0ZxiJH6T9iQ0crNSnUOOPo',
    appId: '1:152990228183:ios:1da0bfa1ce1109e5155a92',
    messagingSenderId: '152990228183',
    projectId: 'bitirme-c0dd9',
    storageBucket: 'bitirme-c0dd9.firebasestorage.app',
    iosClientId: '152990228183-mf34pbmpvs84gn2f2tq100u87f0vg61o.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8iNsdD7ZNT8IsG8CWrBj4CvBTgX5Wosc',
    appId: '1:152990228183:web:fae13df16c9a4b76155a92',
    messagingSenderId: '152990228183',
    projectId: 'bitirme-c0dd9',
    authDomain: 'bitirme-c0dd9.firebaseapp.com',
    storageBucket: 'bitirme-c0dd9.firebasestorage.app',
  );
}
